FROM ghcr.io/astral-sh/uv:python3.12-bookworm-slim

WORKDIR /app

COPY pyproject.toml uv.lock ./

ENV UV_SYSTEM_PYTHON=1
RUN uv sync --frozen --no-dev

COPY dashboard/ ./dashboard/
# This is a hack for now. Replace sqlite with postgres for scalability
COPY finance.db ./

ENV PORT=8501
EXPOSE ${PORT}

CMD ["uv", "run", "streamlit", "run", "dashboard/app.py", "--server.port=8501", "--server.address=0.0.0.0"]